const CONFIG={lineUrl:'#contact',formEndpoint:'',phone:'042-650-6260'};
const works=[
 {title:'壁・クロス',en:'WALL & CLOTH',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=88',text:'汚れや剥がれが気になる壁紙の張り替え、壁材を使った内装仕上げ。'},
 {title:'天井仕上げ・軽天',en:'CEILING & LGS',image:'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=86',text:'壁・天井の下地となる軽量鉄骨の骨組みと、天井まわりの仕上げ。'},
 {title:'床・間仕切り',en:'FLOOR & PARTITION',image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=88',text:'用途に合わせた床仕上げや、部屋・店舗のレイアウト変更に伴う間仕切り。'}
];
const qa=[['小さな工事でも相談できますか？','工事の規模や内容によって対応可否が異なります。まずは場所と現在の状態をお知らせください。'],['工事内容が決まっていなくても大丈夫ですか？','はい。「壁の汚れが気になる」「部屋を仕切りたい」など、今のお悩みからご相談ください。'],['どの地域まで来てもらえますか？','八王子市を拠点としています。具体的な対応地域は、工事内容と住所を確認のうえご案内します。'],['住宅以外も相談できますか？','公開情報では内装仕上工事を主な対応工事としています。店舗等についても、用途と工事内容を添えてお問い合わせください。']];
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>',lineIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 11.3c0 4.1-4 7.5-9 7.5-.8 0-1.6-.1-2.3-.3L5 21l1.2-4C4.2 15.6 3 13.6 3 11.3c0-4.2 4-7.6 9-7.6s9 3.4 9 7.6Z"/></svg>';
document.querySelector('#app').innerHTML=`<main>
<section class="hero" id="top"><img class="hero-bg" src="https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=2000&q=90" alt="明るく整えられた住宅内装のイメージ"><div class="hero-shade"></div><div class="hero-copy reveal"><p>INTERIOR FINISHING · HACHIOJI</p><h1>暮らしの輪郭を、<br>内装から整える。</h1><span>Walls, ceilings and floors<br>finished for everyday life.</span></div><small>IMAGE PHOTO</small></section>
<header class="nav"><a class="brand" href="#top"><b>LH</b><span>有限会社<br>エルエイチコンストラクション</span></a><nav><a href="#philosophy">私たちについて</a><a href="#works">対応工事</a><a href="#flow">ご相談の流れ</a><a href="#company">会社概要</a><a href="#faq">よくある質問</a></nav><a class="contact-pill" href="#contact">CONTACT ${arrow}</a><button class="menu" aria-label="メニュー" aria-expanded="false"><i></i><i></i></button></header>
<section class="section philosophy" id="philosophy"><div class="section-title reveal"><span>01</span><div><p>OUR APPROACH</p><h2>「どこを直せばいい？」<br>その段階から、<br>話せる内装屋です。</h2></div></div><div class="feature-image reveal"><img src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=88" alt="落ち着いた住宅内装のイメージ"><span>IMAGE PHOTO</span></div><div class="strengths"><article class="reveal"><b>01</b><h3>工事名が分からなくても<br>相談できます</h3><p>「壁が汚れている」「部屋を仕切りたい」など、気になる場所と希望をお聞きし、必要な工事を整理します。</p></article><article class="reveal"><b>02</b><h3>壁・天井・床を<br>まとめて相談</h3><p>軽天、壁張り、天井・床仕上げ、間仕切り、防音、畳・ふすまなど、内装仕上工事についてご相談いただけます。</p></article><article class="reveal"><b>03</b><h3>八王子市を拠点に<br>内容を確認して対応</h3><p>所在地は東京都八王子市川町。対応地域や工事の可否は、場所と内容を確認したうえでご案内します。</p></article></div></section>
<section class="section lavender works" id="works"><div class="section-title light reveal"><span>02</span><div><p>WHAT WE DO</p><h2>相談できる<br>内装工事</h2></div></div><div class="work-list">${works.map((w,i)=>`<article class="reveal"><img src="${w.image}" alt="${w.title}のイメージ"><div><span>${w.en}</span><h3>${w.title}</h3><p>${w.text}</p><a href="#contact">相談する ${arrow}</a></div><small>0${i+1} · IMAGE PHOTO</small></article>`).join('')}</div><div class="more-works reveal"><p>そのほかの公開上の対応工事</p><div><span>防音工事</span><span>畳・ふすま</span><span>内装仕上工事全般</span><span>まだ内容が決まっていない相談</span></div></div></section>
<section class="section flow" id="flow"><div class="section-title reveal"><span>03</span><div><p>HOW IT WORKS</p><h2>ご相談から<br>施工まで</h2></div></div><ol>${[['お問い合わせ','電話またはフォームから、気になる場所や工事内容をお知らせください。'],['内容・現地確認','ご希望を伺い、必要に応じて現地の状態や寸法を確認します。'],['工事内容のご案内','確認内容をもとに、工事範囲や進め方をご案内します。'],['施工','日程を調整し、周囲に配慮しながら内装工事を進めます。']].map(([h,p],i)=>`<li class="reveal"><b>0${i+1}</b><div><h3>${h}</h3><p>${p}</p></div></li>`).join('')}</ol></section>
<section class="section lavender company" id="company"><div class="section-title light reveal"><span>04</span><div><p>COMPANY PROFILE</p><h2>会社概要</h2></div></div><img class="company-image reveal" src="https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1800&q=88" alt="内装事業者のオフィスイメージ"><div class="company-card reveal"><h3>有限会社<br>エルエイチコンストラクション</h3><dl><dt>代表者</dt><dd>井上 守</dd><dt>所在地</dt><dd>〒193-0821<br>東京都八王子市川町836</dd><dt>電話番号</dt><dd><a href="tel:0426506260">042-650-6260</a></dd><dt>資本金</dt><dd>5,000千円</dd><dt>主な対応工事</dt><dd>内装仕上工事</dd></dl><p>※公開されている建設業者情報をもとに掲載しています。</p></div></section>
<section class="section faq" id="faq"><div class="section-title reveal"><span>05</span><div><p>FAQ</p><h2>よくある<br>ご質問</h2></div></div><div class="faq-list">${qa.map(([q,a],i)=>`<details class="reveal" ${i===0?'open':''}><summary><b>Q.</b>${q}<span>⌄</span></summary><div class="answer"><b>A.</b><p>${a}</p></div></details>`).join('')}</div></section>
<a class="line-float js-line" href="${CONFIG.lineUrl}">${lineIcon} LINEで相談</a>
<footer class="footer" id="contact"><div class="footer-left reveal"><p class="footer-label">CONTACT</p><h2>気になる場所を、<br>まず教えてください。</h2><p>まだ具体的に決まっていなくても構いません。<br>分かる範囲でお知らせください。</p><a class="footer-phone" href="tel:0426506260"><small>お電話でのご相談</small>${CONFIG.phone}</a><address>〒193-0821<br>東京都八王子市川町836</address><small>© LH CONSTRUCTION</small></div><form id="inquiry-form" action="${CONFIG.formEndpoint}" method="POST" novalidate class="reveal"><p>——　CONTACT FORM</p><h2>お問い合わせ</h2><label>お名前 <em>*</em><input name="name" autocomplete="name" required placeholder="お名前を入力してください"></label><div class="two"><label>電話番号 <em>*</em><input name="tel" type="tel" autocomplete="tel" required placeholder="090-0000-0000"></label><label>メールアドレス <em>*</em><input name="email" type="email" autocomplete="email" required placeholder="mail@example.com"></label></div><label>お住まいの地域<input name="area" autocomplete="address-level2" placeholder="例）八王子市"></label><label>希望する工事内容 <em>*</em><select name="work" required><option value="">選択してください</option>${works.map(w=>`<option>${w.title}</option>`).join('')}<option>防音工事</option><option>畳・ふすま</option><option>その他の内装工事</option><option>まだ具体的に決まっていない</option></select></label><label>お問い合わせ内容 <em>*</em><textarea name="message" required placeholder="気になる場所や状態、ご希望などをご記入ください"></textarea></label><label class="check"><input type="checkbox" required>入力内容を問い合わせ対応のために利用することに同意します。</label><p class="form-status" role="status" aria-live="polite"></p><button type="submit">無料で相談する ${arrow}</button></form></footer><div class="mobile-cta"><a class="js-line" href="${CONFIG.lineUrl}">${lineIcon} LINEで相談</a><a href="#contact">お問い合わせ</a></div></main>`;
const menu=document.querySelector('.menu'),nav=document.querySelector('.nav nav');menu.addEventListener('click',()=>{const o=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!o));nav.classList.toggle('open',!o)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));document.querySelectorAll('.js-line').forEach(a=>a.addEventListener('click',e=>{if(CONFIG.lineUrl==='#contact'){e.preventDefault();document.querySelector('#contact').scrollIntoView({behavior:'smooth'});document.querySelector('.form-status').textContent='LINE公式URLは準備中です。フォームまたはお電話をご利用ください。'}}));const form=document.querySelector('#inquiry-form');form.addEventListener('submit',e=>{const s=form.querySelector('.form-status');if(!form.checkValidity()){e.preventDefault();form.reportValidity();s.textContent='必須項目をご確認ください。';return}if(!CONFIG.formEndpoint){e.preventDefault();s.textContent='送信先の設定中です。お急ぎの場合は 042-650-6260 へお電話ください。'}});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
